### PR TITLE
Add delete address command and bug fixes

### LINKED ISSUE #61: Edit does not change public address
Public address not allowed to be edited by itself. `edit 6 /paBTC>123` does not work and instead displays an error message

### LINKED ISSUE #65: Add command crashing after not putting tokenizer
add command would crash if inputting `add n/.... pa/BTC`

### PR DESCRIPTION
**Pull request by TheRareFox**
This commit 1e20419a6a63737d998ec0c06fb15c7386bca3f0 fixes #61
This commit 74a56cbea63b42990273651435acd43e0606d00a fixes #65 
This commit 500bd183d3d6d088a31502c4aba254ba40e6fe9d implements #26

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -218,7 +217,7 @@ public Optional<Map<Network, Set<PublicAddress>>> getPublicAddresses() {
          * A defensive copy of {@code publicAddresses} is used internally.
          */
         public void setPublicAddresses(Map<Network, Set<PublicAddress>> publicAddresses) {
-            this.publicAddresses = (publicAddresses != null) ? new HashMap<>(publicAddresses) : null;
+            this.publicAddresses = publicAddresses;
```
Comment (Airiinnn) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:220]: This is very dangerous as publicAddress can now be changed from outside the class. Is there a reason for this change?

File: src/main/java/seedu/address/logic/parser/DeleteAddressCommandParser.java
Comment (Airiinnn) [inline src/main/java/seedu/address/logic/parser/DeleteAddressCommandParser.java:1]: DeletePublicAddressCommandParser might be better. Since there is also an address field in Person.

File: src/main/java/seedu/address/model/person/Person.java [hunk 2]
```diff
@@ -64,10 +64,34 @@ public Set<PublicAddress> getPublicAddressesByNetwork(Network network) {
...
+
+    /**
+     * Gets the current Public address map
+     * Should be replaced with a better method in the future
+     *
+     * @return publicAddresses
+     */
     public Map<Network, Set<PublicAddress>> getPublicAddresses() {
-        return Collections.unmodifiableMap(publicAddresses);
+        return this.publicAddresses;
```
Comment (Airiinnn) [inline src/main/java/seedu/address/model/person/Person.java:81]: Same thing here, much safer to return copy / unmodifiable.

File: src/main/java/seedu/address/model/person/Person.java [hunk 3]
```diff
@@ -64,10 +64,34 @@ public Set<PublicAddress> getPublicAddressesByNetwork(Network network) {
...
     }
 
+    /**
+     * Sets the Public address to a new one
+     * Should be replaced with a better method in the future
+     *
+     * @param addresses
+     */
+    public void setPublicAddresses(Map<Network, Set<PublicAddress>> addresses) {
+        this.publicAddresses = addresses;
```
Comment (Airiinnn) [inline src/main/java/seedu/address/model/person/Person.java:91]: Same thing here

**Review by Airiinnn — CHANGES_REQUESTED** [review]
Potential bugs may arise from getting and setting Map fields directly. Would be much safer to make a copy instead. Is there a reason that necessitates direct access?

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 4]
```diff
@@ -190,4 +194,21 @@ public static Set<Tag> parseTags(Collection<String> tags) throws ParseException
         }
         return tagSet;
     }
+
+    /**
+     * Parses a {@code String tag} into a {@code Tag}.
```
Comment (Airiinnn) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:199]: I think you missed this javadoc comment

Comment (TheRareFox) [reply src/main/java/seedu/address/logic/parser/ParserUtil.java]: Fixed

File: src/main/java/seedu/address/model/person/Person.java (hunk 3 above)
Comment (TheRareFox) [reply src/main/java/seedu/address/model/person/Person.java]: Fixed in commit 39c5ce2c8be90a5c6695fc5696ac1f59b783b4e8

File: src/main/java/seedu/address/model/person/Person.java (hunk 2 above)
Comment (TheRareFox) [reply src/main/java/seedu/address/model/person/Person.java]: Fixed in commit 39c5ce2c8be90a5c6695fc5696ac1f59b783b4e8

File: src/main/java/seedu/address/logic/parser/DeleteAddressCommandParser.java
Comment (TheRareFox) [reply src/main/java/seedu/address/logic/parser/DeleteAddressCommandParser.java:1]: Fixed in commit 39c5ce2c8be90a5c6695fc5696ac1f59b783b4e8

File: src/main/java/seedu/address/logic/commands/EditCommand.java (hunk 1 above)
Comment (TheRareFox) [reply src/main/java/seedu/address/logic/commands/EditCommand.java]: Fixed in commit 39c5ce2c8be90a5c6695fc5696ac1f59b783b4e8
